// LOCALHOST 
### get all contacts
GET http://localhost:8080/contacts

### Get single contact by Id
GET http://localhost:8080/contacts/63cc041a1b1ea223f39615c1

### Create a contact 
POST http://localhost:8080/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Vernon",
    "lastName": "Blye",
    "email": "vblye@test.com",
    "favoriteColor": "Blue",
    "birthday": "03/28/1960" 
}
  
### Update a contact 
PUT http://localhost:8080/contacts/63de0cd8f94789d621e37652 HTTP/1.1
content-type: application/json

{
    "firstName": "Vernon",
    "lastName": "Blye",
    "email": "vblye@test.com",
    "favoriteColor": "Lavendar",
    "birthday": "03/28/1960" 
}

### Delete a contact
DELETE http://localhost:8080/contacts/63de0cd8f94789d621e37652 HTTP/1.1


// PRODUCTION Deploy 

### Get all contacts
GET https://cse341-w2.onrender.com/contacts/

### Get a single contact by Id
GET https://cse341-w2.onrender.com/contacts/63cc041a1b1ea223f39615c1

### Create a contact 
POST https://cse341-w2.onrender.com/ HTTP/1.1
content-type: application/json

{
  "firstName": "Vernon",
  "lastName": "Blye",
  "email": "vblye@test.com",
  "favoriteColor": "Blue",
  "birthday": "03/28/1960"
}
  
### Update a contact 
PUT https://cse341-w2.onrender.com/63ddd8c7c173fc9a9d2477b9 HTTPS/1.1
content-type: application/json

{
    "firstName": "Billi",
    "lastName": "Blye",
    "email": "bblye@test.com",
    "favoriteColor": "Purple",
    "birthday": "03/28/1960"
  }

### Delete a contact
DELETE https://cse341-w2.onrender.com/63ddfd432bd19ef0ed2b9611 HTTPS/1.1